import time
print("write /start | напишите /старт")
input()
print("enter the password to enter Russian databases (password: putin_huylo) | введите пароль для входа российских датабаз (пароль: putin_huylo)")
input()
print("Signed in, want to start leaking passwords? [y/n] | вход выполнен, хотите начать утечку паролей? [y/n]")
input()
print("the beginning of the password leak is praised, starting | начало утечки пароля хвалят, начинаю")
time.sleep(3)
print("loading | загрузка")
time.sleep(3)
print("|----1%----|")
time.sleep(1)
print("|----3%----|")
time.sleep(1)
print("|----5%----|")
time.sleep(1)
print("|----7%----|")
time.sleep(1)
print("|----10%----|")
time.sleep(1)
print("|----12%----|")
time.sleep(1)
print("|----15%----|")
time.sleep(1)
print("|----17%----|")
time.sleep(1)
print("|----20%----|")
time.sleep(1)
print("|----22%----|")
time.sleep(1)
print("|----24%----|")
time.sleep(1)
print("|----28%----|")
time.sleep(1)
print("|----31%----|")
time.sleep(1)
print("|----40%----|")
time.sleep(1)
print("|----45%----|")
time.sleep(1)
print("|----52%----|")
time.sleep(1)
print("|----53%----|")
time.sleep(1)
print("|----59%----|")
time.sleep(1)
print("|----67%----|")
time.sleep(1)
print("|----74%----|")
time.sleep(1)
print("|----78%----|")
time.sleep(1)
print("|----82%----|")
time.sleep(1)
print("|----88%----|")
time.sleep(1)
print("|----93%----|")
time.sleep(1)
print("|----97%----|")
time.sleep(1)
print("|----99%----|")
time.sleep(1)
print("|----100%----|")
time.sleep(1)
print("successful, start password leaks |  успешно, начало утечек паролей")
time.sleep(2)
print("gasprom : 4823scvdsfwrwi")
time.sleep(0.5)
print("yandex : 87tf3eg23djsi")
time.sleep(0.5)
print("mail.ru : 12u8eyh328dhg2uwq2")
time.sleep(0.5)
print("marysya : 13921hhch12h83")
time.sleep(0.5)
print("ICQ : 32148924732R8SUDFDSK")
time.sleep(0.5)
print("avito : 21908h12k12fs")
time.sleep(0.5)
print("vk.com : 0210x34h2sj")
time.sleep(0.5)
print("ozon : 21c3b12s312ajk12")
time.sleep(0.5)
print("RCS : 812H34H82H37JA1")
time.sleep(0.5)
print("okko sport : 8h123121819hhfnnnc")
time.sleep(0.5)
print("SberBank : 0198hh1293j12")
time.sleep(0.5)
print("AYYA : 2131H203JNCBAX")
time.sleep(0.5)
print("AlfaBank : 1831203kz100z")
time.sleep(0.5)
print("2GIS : dhsjdh1238192300xx")

